### PR TITLE
intial packet number should be 0.

### LINKED ISSUE #850: Remove initial packet number randomization
With the resolution of #693 we no longer need initial packet numbers to be randomized.

### PR DESCRIPTION
**Pull request by mcmanus**
Closes #850

### CODE REVIEW

**Comment by mikkelfj** [comment]
It is not clear to me if this increment by one is only in the clear text or it applies to all packet numbers, including 1-RTT?

**Comment by RyanAtGoogle** [comment]
I don't want to pile on, but please, 1 instead of 0. It's convenient in code to have a sentinel value for an invalid packet number and the obvious choices are 0 and MAX_INT64. 0 has the nice virtual of being obvious when printed in base10, whereas MAX_INT64 is just some random big number. In addition, 0 has the property of being less than valid packet number. So this allows you to write code like:

  if current_packet.packet_number > largest_received_packet_:
    UpdateNewLargestPacket()

Without needing to explicitly handle the case where largest_received_packet_ is MAX_INT64.

**Comment by ianswett** [comment]
Agreed, let's make this 1.

**Comment by ekr** [comment]
Note that if we are starting at 0, you can just use int64_t, tear the
connection down at 2^{63} and use -1 as a sentinel.

-Ekr

**Comment by nibanks** [comment]
We already have an issue tracking whether or not to allow 0: #832. I feel the discussion is better served if we keep it in that one place.

**Comment by mcmanus** [comment]
packet number 0 is already legal (the random range is between 0 and 2^31-1). @nibanks is right, if we want to change that do it in another issue - this PR is to remove the randomness.

**Comment by mcmanus** [comment]
@mikkelfj all packet numbers

**Comment by mcmanus** [comment]
`if current_packet.packet_number > largest_received_packet_:
UpdateNewLargestPacket()`

??

if current_packet.packet_number >= next_expected_packet 
 Update()

**Comment by RyanAtGoogle** [comment]
"if current_packet.packet_number >= next_expected_packet 
  Update()"

Ok fine, this is what I get for not using a real example :) >= works for the particular case I described. But there are cases in the code where we may see the same packet number multiple times but only want to do an operation when we've seen a new largest number and not if we're merely seeing the same largest number against. In those cases >= does not work.

**Comment by marten-seemann** [comment]
We would have the same problems in quic-go. Excluding 0 makes the code so much easier, please make it 1.

**Comment by MikeBishop** [comment]
Regardless of the outcome of the 0 vs. 1 debate, this is stale from the updated Packet names from #847.

**Pull request closed without merging**
