### PR TITLE
Change packet number encoding example

### PR DESCRIPTION
**Pull request by martinthomson**
For a reason I didn't bother to investigate this was wrong.

@MikeBishop, please double check.  Anyone else who wants to double
check, the extra effort would be appreciated.

### CODE REVIEW

**Comment by larseggert** [comment]
Is there an issue associated with this?

**Comment by MikeBishop** [comment]
This appears to check out, but obviously my math is suspect, having written the original example.  :-)

**Comment by bradfordwetmore** [comment]
I am the person who pointed this out to @MikeBishop last night.  These new numbers look correct to me. 

 Note, I am not involved with the draft writing, so can't approve this change.

Thanks for addressing.

**Comment by martinthomson** [comment]
Whether or not you can approve, I value the extra validation.  At this stage, we can't afford to make this sort of mistake.  And Mike, it's on me as much as you for not checking your numbers originally :)

**Pull request merged**
