### PR TITLE
Change retransmittable to Ack-eliciting

### LINKED ISSUE #1595: Rename "retransmittable" frames and packets
The word retransmittable is used in the recovery draft for both frames and packets that cause an ACK frame to be sent in response to their receipt.

This is really misleading, because QUIC never retransmits packets(except maybe connection close) and only sometimes retransmits frames.

Ideally we'd have different words for the frames and the packets containing those frames, but at a minimum I want to stop using retransmittable.

Previous suggestions:
- Ackable - I didn't like this before, but it's strictly better than retransmittable.
- Reliable - Maybe a good term for packets, less good for frames?
- Needs Acknowledgement - Verbose, but correct.  Possibly abbreviated to Nack for maximum confusion :)
- Persistent

I'm want to change retransmittable to something else before the next drafts, so please suggest alternatives now and I'll write a PR for whatever people hate the least.

### PR DESCRIPTION
**Pull request by ianswett**
Ack-eliciting is slightly shorter than retransmittable and seems as accurate as anything we have.

Fixes #1595

### CODE REVIEW

**Comment by ianswett** [comment]
I'm not set on this being what we go with, but I think it reads reasonably well and I'm really unhappy with retransmittable, since I think it's just confusing.  If there's another alternative you'd like to see me create a PR for, feel free to suggest it.

**Comment by dtikhonov** [comment]
Does the English language have a suffix that means that something _must_ be done ("ack`$foo`") rather than that _can_ be done ("ackable")?  What's `$foo`? 😖

**Comment by dtikhonov** [comment]
Based on [this list of English suffixes](https://www.learnthat.org/pages/view/suffix.html), I propose that we use _ackent_ instead of ack-eliciting.  The suffix _ENT_ means "one who performs/causes."

Thus, instead of

> Packets that contain **ack-eliciting** frames elicit an ACK from the receiver within the maximum ack delay and are called **ack-eliciting** packets.

we will have

> Packets that contain **ackent** frames elicit an ACK from the receiver within the maximum ack delay and are called **ackent** packets.

**Comment by mikkelfj** [comment]
resilient

> Packets that contain resilient frames elicit an ACK from the receiver within the maximum ack delay and are called resilient packets.

unforgettable
https://www.youtube.com/watch?v=2HSt7LWsm-A

> Packets that contain unforgettable frames elicit an ACK from the receiver within the maximum ack delay and are called unforgettable packets.

unmissable

> Packets that contain unmissable frames elicit an ACK from the receiver within the maximum ack delay and are called unmissable packets.

robust

> Packets that contain robust frames elicit an ACK from the receiver within the maximum ack delay and are called robust packets.

stateful

> Packets that contain stateful frames elicit an ACK from the receiver within the maximum ack delay and are called stateful packets.

**Comment by dtikhonov** [comment]
@mikkelfj, my suggestion was in earnest.

**Comment by mikkelfj** [comment]
Mine was only half in jest. I kind of like resilient.

**Pull request closed without merging**
