### PR TITLE
Negative base values are invalid

### LINKED ISSUE #4938: negative base values
[Section 4.5.1.2 of QPACK](https://quicwg.org/base-drafts/draft-ietf-quic-qpack.html#name-base) states that Base is calculated as:
```
   if S == 0:
      Base = ReqInsertCount + DeltaBase
   else:
      Base = ReqInsertCount - DeltaBase - 1
```

As Base is defined as an index of a table, I tend to believe that it is assumed to be non-negative. Am I correct?

I am asking this because I cannot find any statement that states as such, even though [section 7.4](https://quicwg.org/base-drafts/draft-ietf-quic-qpack.html#name-implementation-limits) states that decoders might refuse very _large_ values.

I understand that it might be too late to consider changes to the draft, but would like to see if we have consensus that QPACK encoders are prohibited from generating an Encoded Field Section Prefix that causes Base to become negative.

### PR DESCRIPTION
**Pull request by martinthomson**
Happy to use MAY here, which would be fine in terms of achieving our goals.

Signed math is entirely valid here, but it introduces other problems; as there is no need to go negative (it's less efficient), this seems safest.

This is what people have implemented - at least in some cases - but we should confirm.  

Closes #4938.

### CODE REVIEW

**Review by MikeBishop — APPROVED** [review]
I'm also ambivalent between MUST and MAY.  Our principle is that easily detected errors are mandatory and difficult to detect are optional, though, so MUST is appropriate by that rule.

**Comment by LPardue** [comment]
@kazuho does this address the issue you raised on #4938?

@afrind any thoughts as the document editor?

**Review by afrind — APPROVED** [review]
I like the MUST there.  

Do we need to say anything about the S=0 case overflowing (eg: a prefix with a very large DeltaBase that would wrap)?  I'm sort of inclined to leave it.

**Comment by martinthomson** [comment]
Is that X>MaxEntries? Or X>2^64 ( or whatever maximum your implementation might want given that your tables can be sized to allow smaller representations)…?

**Review by kazuho — APPROVED** [review]

**Comment by kazuho** [comment]
@LPardue
> does this address the issue you raised on #4938?

Thank you. It does.

Re overflow (of integers), +1 to _not_ saying anything.

Delta Base uses HPACK integer representation. [RFC 7541 section 7.1](https://datatracker.ietf.org/doc/html/rfc7541#section-7.4) already has cautionary text regarding large values.

**Pull request merged**
