### PR TITLE
pseudo-headers ain't extensible

### PR DESCRIPTION
**Pull request by LPardue**

### CODE REVIEW

**Review by ianswett — APPROVED** [review]

**Review by martinduke — APPROVED** [review]

**Comment by martinthomson** [comment]
So this is a curious one.  @mnot said something very specific, which matched the original text.  That was "The extensibility point that 8441 uses is SETTINGS, which negotiates a change in the operation of the protocol on a connection-by-connection basis."  What this does is effectively prohibit this.

We're in the process of discussing what to do about this for HTTP/2 and the flat prohibition there is something people have trouble with.  What Mike wrote here is a response to that.  I don't think we need this.

**Comment by LPardue** [comment]
Rejecting this PR is a fine editor action if that's the right thing to do.

Having H2 and H3 inconsistent with each other seems like a bad outcome.

**Comment by MikeBishop** [comment]
Fortunately, there's an easy fix to that in draft-thomson-httpbis-http2bis.  😉

**Comment by janaiyengar** [comment]
I'm not familiar with the history here, but this seems like a design change. I don't think editor action is the right course here.

**Review by janaiyengar — APPROVED** [review]

**Comment by janaiyengar** [comment]
@lucasp: Can you close this out to reduce PR clutter?

**Pull request closed without merging**
