### PR TITLE
Add 'time' to latest_in_flight_lost

### PR DESCRIPTION
**Pull request by ianswett**
I'm not sure this is the best name, but I think adding 'time' to the variable makes this easier to read, particularly since the variable is initialized to 0, which is not really a time.

Follow-up to #4426

### CODE REVIEW

**Comment by larseggert** [comment]
time_of_latest_in_flight_loss?

**Comment by ianswett** [comment]
@larseggert SGTM, PTAL

**Review by janaiyengar — APPROVED** [review]
This isn't the time of the loss, it's the time that this packet was sent. Which is why I left `time` out of the name entirely. Maybe `sent_time_of_latest_in_flight_loss` if you want to be really accurate?

Alternatively, it's a local variable. You could do something like:
```
// t records the send time of the latest inflight packet
// that was marked as lost.
t = 0
```

**Comment by ianswett** [comment]
How about sent_time_of_latest_loss?

Technically, packets that aren't in-flight are never declared lost so I don't think in_flight is necessary in the variable name.

**Comment by janaiyengar** [comment]
@ianswett - that works!

**Comment by martinthomson** [comment]
or `sent_time_of_last_loss` if you need two more bytes back

**Comment by janaiyengar** [comment]
Not for this PR, but this does point out a slight ambiguity in the description of persistent congestion, which has as its first condition: `all packets, across all packet number spaces, sent between the send times of these two packets are declared lost`

If non-ack-eliciting packets are never declared lost, that makes this text a bit odd to square away.

**Comment by martinthomson** [comment]
I don't think that's a problem.  When you declare the trailing ack-eliciting packet lost, all packets sent in the same packet number space before the lost packet will also be declared lost (unless they were acknowledged, of course).

The only risk is that there might be packets (both ack-eliciting and non-ack-eliciting) from a different packet number space that aren't declared lost.  Mostly, this is because that space might not have newer packets are are acknowledged.  I think that we can tolerate that little bit of infidelity.

**Comment by ianswett** [comment]
I took @martinthomson last suggestion of sent_time_of_last_loss.  Feel free to merge whenever(sooner the better I expect).

**Comment by janaiyengar** [comment]
@martinthomson : Technically, non-ack-eliciting packets are never "declared lost". I've proposed a fix in #4437.

**Pull request merged**
