### PR TITLE
missing cross ref

### PR DESCRIPTION
**Pull request by reschke**

### CODE REVIEW

**Comment by martinthomson** [comment]
I think that the intent here is not to reference h2, but to use CONNECTION_CLOSE.  @MikeBishop?

**Comment by MikeBishop** [comment]
Correct; this should be a reference to 6.1, not RFC 7540.

**Comment by reschke** [comment]
I see. I thought it was because the problem goes back to early versions, and that section number apparently never existed...

**Comment by MikeBishop** [comment]
Merged manually, fixed to local ref.

**Pull request merged**
