### PR TITLE
version negotiation isn't low latency, so remove it

### PR DESCRIPTION
**Pull request by martinthomson**

### CODE REVIEW

**Comment by martinthomson** [comment]
Ahh, I missed a step.  Incoming...

**Comment by martinthomson** [comment]
:) IPv4 is also low latency by the same measure, it just doesn't really have a "negotiation" piece.

I think that the main point is that it's redundant with the "low latency connection setup" thing.  A truly low latency version negotiation would allow for some progress on the rest of the handshake in parallel.  But that requires a greater commitment to a given packet format.

**Comment by janaiyengar** [comment]
I'd like to leave the section there; I think it's fine to remove the "low-latency" part. As a transport protocol, QUIC supports version negotiation, which is a novelty among IETF transports.

**Comment by martinthomson** [comment]
I think that the text is problematic if it remains.  You can say that it has version negotiation, but that doesn't need explanatory text.

For instance, this is not an unqualified advantage: "incentivizes servers to not lag behind clients in deployment of newer versions".  That says to servers that they have to keep up with Google if I want to get the latency benefits of the protocol (at least for first-time connections).

I'll open a separate PR for the text.

**Pull request closed without merging**
