### PR TITLE
Update Initial salt, Retry keys, and samples for -29

### PR DESCRIPTION
**Pull request by martinthomson**

### CODE REVIEW

**Comment by DavidSchinazi** [comment]
Any chance we could also update the initial salt?

**Comment by martinthomson** [comment]
I was saving that for the final version, by popular demand.  If you have a reason to change, then I can do that (I'll also want to update the keys for Retry in that case).

**Comment by DavidSchinazi** [comment]
With Google's QUIC deployment, we're already experiencing version ossification due to middleboxes inspecting initial packets - some of our traffic is stuck on older versions of GoogleQUIC because of this. Changing the salts every time we change the version number will help remind everyone that this is not an ossified aspect of the protocol. The cost to implementors is pretty much zero.

@rpaulo out of curiosity, why the pushback?

**Comment by marten-seemann** [comment]
What @DavidSchinazi says makes sense to me, so I would be in favor of shipping draft-29 with new salts.

**Comment by marten-seemann** [comment]
I updated the salts and the test vectors in quic-go, and I can confirm that the values match.

**Pull request merged**
