### PR TITLE
remove outdated text about version negotiation

### PR DESCRIPTION
**Pull request by marten-seemann**

### CODE REVIEW

**Comment by DavidSchinazi** [comment]
I must have missed this when making the PR to remove the version negotiation text. Thanks @marten-seemann !

**Comment by rpaulo** [comment]
Fixes #2737

**Comment by marten-seemann** [comment]
I wasn’t aware that there was an issue. Sorry for that!

**Comment by rpaulo** [comment]
No worries, thanks for doing this!

**Pull request merged**
