### PR TITLE
Move version

### PR DESCRIPTION
**Pull request by martinthomson**

### CODE REVIEW

**Comment by ianswett** [comment]
Closes Issue #1166

**Comment by mikkelfj** [comment]
If VNEG is an invariant and easily observable, why not fix the unused bits to 0 for this specifical instance where version is 0. This would make it trivial to test for VNEG. It's not like VNEG could later use the unused bits for anything useful later on.

**Comment by MikeBishop** [comment]
See #963 for the previous round of discussion on that topic, but basically.  We don't want a packet type fixed across versions -- particularly since even the fact that the field *is* a packet type isn't actually an invariant.  The low bits of the first byte are simply version-dependent.

**Comment by martinthomson** [comment]
Mikkel's point here, which I think is valid, is that for *version 0*, we could define the semantics of the type/unused bits.  Requiring the value to be 0 as part of that would be reasonable and might allow for other values to carry some other sort of signal (though what that might be is hard to know right now).

**Pull request merged**
