### PR TITLE
PTO is restarted on handshake confirmation

### LINKED ISSUE #4710: Ben Kaduk's Recovery Comment 3
@kaduk said:

> Section 6.2.1
> 
> > A sender SHOULD restart its PTO timer every time an ack-eliciting
> > packet is sent or acknowledged, when the handshake is confirmed
> > (Section 4.1.2 of [QUIC-TLS]), or when Initial or Handshake keys are
> > discarded (Section 4.9 of [QUIC-TLS]).  [...]
> 
> If I understand correctly, "handshake is confirmed" and "handshake keys
> are discarded" occur simultaneously, thus it is redundant to list both.

### PR DESCRIPTION
**Pull request by janaiyengar**
Closes #4710.

### CODE REVIEW

**Review by martinthomson — APPROVED** [review]
Perfect.

**Review by ianswett — CHANGES_REQUESTED** [review]
I don't think this is correct, since when Initial or Handshake keys are discarded, if the PTO was set based on one of those PN spaces, clearly the PTO would need to be reset.

**Comment by martinthomson** [comment]
Ian is right, we would lose the Initial discard condition.  Drop the Handshake key drop condition.

**Review by martinthomson — APPROVED** [review]

**Comment by janaiyengar** [comment]
@ianswett -- you're right, but I think that only applies to Initial here, since hs confirmed is the same as hs keys getting dropped. Take a look at the new text.

**Review by martinthomson — APPROVED** [review]

**Review by ianswett — APPROVED** [review]

**Pull request merged**
