### PR TITLE
Makefile: add target to generate tags for I-D sections

### PR DESCRIPTION
**Pull request by dtikhonov**

### CODE REVIEW

**Comment by MikeBishop** [comment]
This seems like it might be a more generally useful addition to https://github.com/martinthomson/i-d-template, rather than being specific to QUIC.

**Comment by dtikhonov** [comment]
Superceded by PR #1302 -- closing.

**Comment by MikeBishop** [comment]
Exactly: my point is that you're making the PR into QUIC's local Makefile instead of the template's Makefile.  (Also, you can update PRs by pushing more commits to the same branch, even replacing commits with `--force` if needed.  Updates don't require a new PR.)

**Comment by dtikhonov** [comment]
Well, if you guys don't want it, you can just close PR #1302 and write that you don't want it. I know *I* will still use tags. :)

**Pull request closed without merging**
