### PR TITLE
replace remaining use of "octet" with "byte"

### PR DESCRIPTION
**Pull request by kazuho**
Maybe leftovers from #1921, or newly added text.

### CODE REVIEW

**Review by janaiyengar — APPROVED** [review]
Thanks, @kazuho !

**Review by martinthomson — APPROVED** [review]
How did those slip through!?

**Review by ianswett — APPROVED** [review]

**Review by MikeBishop — APPROVED** [review]
Yes, I think these are mostly new / imported from other docs.

**Comment by kazuho** [comment]
I'm sure the document was touched by his noodly appendage of the Octocat :octocat:

**Pull request merged**
