### PR TITLE
Application-layer close in HTTP/3

### LINKED ISSUE #3428: H3 guidance on CONNECTION_CLOSE does make clear if the type is 0x1c or 0x1d
Draft 25 section 5.3 says:

> An HTTP/3 implementation can immediately close the QUIC connection at
   any time.  This results in sending a QUIC CONNECTION_CLOSE frame to
   the peer; the error code in this frame indicates to the peer why the
   connection is being closed.

This doesn't specifically tie down H3-initiated closure to only use the application variant of CONNECTION_CLOSE (0x1d). This gets a bit strange when combined with later guidance to use H3 error codes or treat unknown error codes as `H3_NO_ERROR`

### PR DESCRIPTION
**Pull request by MikeBishop**
Fixes #3428.

### CODE REVIEW

**Comment by LPardue** [comment]
This goes most of the way to solving my perceived problem. I do wonder if we should also add a little bit more text to section 8 in this paragraph

> An endpoint MAY choose to treat a stream error as a connection error
   under certain circumstances.  Implementations need to consider the
   impact on outstanding requests before making this choice.

Perhaps just a reference e.g. "Implementations need to consider the impact on outstanding requests before making this choice, see {immediate-application-closure}."

**Comment by MikeBishop** [comment]
> > 
> 
> Perhaps just a reference e.g. "Implementations need to consider the impact on outstanding requests before making this choice, see {immediate-application-closure}."

But that section doesn't discuss the impact on outstanding requests, and it seems irrelevant to this topic.  Can you expand on the connection you see?

**Comment by LPardue** [comment]
to me, the choice to promote a stream error to a connection error is the choice to promote it to an immediate application close. Therefore the present statement about "impact on outstanding requests" is really about how to do/decide on graceful close with GOAWAY. If that is not the case, then I don't understand what other consierations my endpoint should make

**Comment by MikeBishop** [comment]
That text was added as a compromise, basically reminding implementations that choosing to blow up their connection will lose any requests in flight, so you should have a good reason.

**Comment by MikeBishop** [comment]
@LPardue, I'm going to go ahead and merge this, since it addresses the original issue and stands by itself.  If you think we need additional text elsewhere, can you open a separate issue?

**Comment by LPardue** [comment]
Sure thing, I'll review again

**Pull request merged**
