### PR TITLE
Text proposal on user land warning about lower layer overhead to addr…

### PR DESCRIPTION
**Pull request by gloinul**
…ess issue #614

### CODE REVIEW

**Comment by MikeBishop** [comment]
"operating system user land" is confusing and seems somewhat colloquial.  Also, it doesn't build because you exceed the line length.  You should rewrap to 80 characters per line.

**Comment by martinthomson** [comment]
I don't think that this is specific to user space implementations.  There are two general classes of concern for user space implementations: timing and MTU.  Neither of these are special enough to warrant text (in my opinion).  In all cases, there are things that lowers layers of the stack might do to degrade service, either by adding delays or encapsulation.  Something like TURN is particularly annoying because the overheads can change over time, but it isn't all that different to a routing change causing packets to be sent on a path with a different MTU (on the contrary, it's actually more predictable).

If the intent is to say that you get better performance if you know more about lower layers of the stack, that is a truism.

**Comment by martinthomson** [comment]
That might be a better approach.  I'd be OK with that.

**Comment by gloinul** [comment]
@martinduke Okay, lets go with your suggestion. I have updated the pull request to only do that change.

**Comment by martinthomson** [comment]
Thanks Magus and Martin!

**Pull request merged**
