### PR TITLE
 Update Initial salt, Retry keys, and samples (#3711) to changelog

### PR DESCRIPTION
**Pull request by alagoutte**

### CODE REVIEW

**Comment by larseggert** [comment]
Shouldn't this be against the -tls changelog?

**Comment by DavidSchinazi** [comment]
Does this need to be in the changelog? The changelog doesn't state that the version number changed, and I view the initial salts as deeply tied to the version number.

**Comment by martinthomson** [comment]
Both Lars and David are right.  

This is a change limited to the -tls draft.

We haven't listed changed keying material in previous changelogs.  Of course, because we haven't been consistent about updating them, I can see why you might want what appears to be an exception called out.

**Comment by alagoutte** [comment]
it is now on tls doc and if you look there is already on changelog info about initial salt update (draft-22...)

**Pull request merged**
