### PR TITLE
define HTTP_UNEXPECTED_GOAWAY

### LINKED ISSUE #1918: Section 4.2.17 references HTTP_UNEXPECTED_GOAWAY which doesn't exist
HTTP_UNEXPECTED_GOAWAY is referenced in section 4.2.17 as the connection error to generate when getting an unexpected goaway, but this is not defined in section 8.

### PR DESCRIPTION
**Pull request by lnicco**
using the first available ID 0x0013

fixes #1918

### CODE REVIEW

**Comment by martinthomson** [comment]
My preference is not to create specific error codes for this, but instead to rely on a more generic error code, but I will let @MikeBishop make that call.

**Comment by MikeBishop** [comment]
Yeah, I'd like to be slightly more generic in situations that have multiple different variants, though probably not as generic as Martin would have me be.

We have HTTP_WRONG_STREAM_DIRECTION for cases where unidirectional streams open in a direction their definition doesn't permit (e.g. clients initiating push streams); maybe we need a HTTP_WRONG_FRAME_DIRECTION for GOAWAY and MAX_PUSH_ID direction issues?

**Comment by lnicco** [comment]
another interesting case is when a second SETTINGS frame gets received, right now we return MALFORMED_FRAME, which is a bit misleading since the frame could be perfectly formed, it's just showing at the wrong time in the wrong place :) 

> If an endpoint receives a second SETTINGS frame, the endpoint MUST respond with a connection error of type HTTP_MALFORMED_FRAME.

how about HTTP_UNEXPECTED_FRAME to catch all the above cases ?

**Comment by MikeBishop** [comment]
That works.

**Pull request merged**
