### PR TITLE
Fix bit prefix verbiage to match figure

### PR DESCRIPTION
**Pull request by dtikhonov**

### CODE REVIEW

**Comment by MikeBishop** [comment]
No, the existing text is correct and the change is incorrect.  The `H` bit is part of the string prefix, so the string prefix is one bit longer than the string's length field.  See the definition of prefixed strings in 5.1.2.

However, I hate how confusing that terminology is, so if you'd like to propose an improvement to that, *please*.  ;-)

**Comment by dtikhonov** [comment]
Sure confused me!  I'll have to reread it.

**Comment by martinthomson** [comment]
Right.  Perhaps it would be better to say "a string literal with an N-bit-prefixed length" or something like that.

**Comment by dtikhonov** [comment]
Having read the document again, I think it is fine as-is. The prefix is described in the _String Literals_ section which comes before the operation definitions and the accompanying figures.

Closing.

**Pull request closed without merging**
