### PR TITLE
http: syntax fixes for quic Alt-Svc parameter

### PR DESCRIPTION
**Pull request by Lekensteyn**
Use the correct ABNF grammar to express repetition and fix the Reserved
Frame Type link.

### CODE REVIEW

**Comment by LPardue** [comment]
There is some baggage with this parameter - https://github.com/quicwg/base-drafts/issues/1093

People were a bit grumpy with changing their parser 18 months ago, I think they might be even grumpier now that we have even more client implementations in the wild.

What is the benefit of this change? I think we need an issue for due process and discussion.

**Comment by RyanAtGoogle** [comment]
Oh joy. This caused me to go look at our parser in Chrome, and realized we're still doing the old (pre 1097) quic=<hex>;quic=<hex> format. So Chrome has work to do no matter how we resolve this. 

That being said, I'd really rather not have two different ways to do this, so +1 to @LPardue 's comment on the motivation.

**Comment by Lekensteyn** [comment]
I can remove the additional unquoted token change and keep this PR purely as editorial fix. Before the PR, the current text does not have correct ABNF grammar.

I added the unquoted token variant since it is permitted (but not required) by the grammar at https://tools.ietf.org/html/rfc7838#section-3
>    parameter     = token "=" ( token / quoted-string )

Since HTTP/3 over QUIC is not the only user of this Alt-Svc header, I can imagine that generic parsers are written such that they already understand the unquoted token value. Thus, adding support for this should not be an additional burden?

I have no strong opinion here. The additional CPU cost of handling both unquoted and quoted forms should be neglible. Disallowing the unquoted form is a restriction of the RFC 7838 grammar.

**Comment by LPardue** [comment]
Let's create a new issue. 

You're correct that non-HTTP/3 implementations might need to handle this - hence the original issue which related back to structured headers (an attempt at defining some best practice in this regard -https://github.com/httpwg/http-extensions/issues/281).

Part of the problem is not CPU cost of DQUOTEs but expressing "a list of versions" and making sure that implementations know how to do that. Alt-Svc defines the parameter syntax but not how to handle repetition of parameters.

**Comment by Lekensteyn** [comment]
I removed the single quote change, this should be a purely editorial fix now. I'll create a new issue for the unquoted parameter value.

**Pull request merged**
