### PR TITLE
Change Idle Timeout to Milliseconds

### LINKED ISSUE #2453: Change Idle Timeout Units of Milliseconds
Currently, the t[ransport parameter for specifying Idle Timeout](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.18.1) is in units of seconds. This seems to be too restrictive and not very future proof. Additionally, from an API perspective, most other timers are settable on the millisecond scale, so it creates a kind of ugly discrepancy between all the different timers settable by the app if just one of them has units of seconds.

I propose we change the units from seconds to milliseconds. The change both for implementations and spec should be minimal, and it makes things (timers) a little more consistent.

### PR DESCRIPTION
**Pull request by nibanks**
Fixes #2453.

### CODE REVIEW

**Comment by martinthomson** [comment]
This is fine, but I think that we want chairs to call it.

**Comment by janaiyengar** [comment]
This falls under the new process, so it's upto the chairs.

**Comment by larseggert** [comment]
Based on the discussion in #2453 I think this has rough consensus. Tagging as such and reassigning.

**Comment by mnot** [comment]
Slow down, we're not in the new process yet. And, in either case, consensus needs to be determined on-list, not in issues.

**Pull request merged**
