### PR TITLE
Adopted QCRAM draft

### PR DESCRIPTION
**Pull request by afrind**
Copied the latest from Buck's repo (https://krasic.github.io/draft-krasic-quic-hpack/draft-krasic-quic-qcram.html), made some minor tweaks to the author block and some fixes to pass lint.

### CODE REVIEW

**Comment by martinthomson** [comment]
This seems OK, but I was expecting a reference from the -http draft to this.  Do you think that you could add that?  It's not important, we can add that later, of course.

Waiting on chairs to approve adoption before we merge.

**Comment by MikeBishop** [comment]
I'll add HTTP changes soonish.

**Comment by krasic** [comment]
Minor nit.   Acknowledgements.    Redundant to include mbiship@ and afrind@ there?

**Comment by larseggert** [comment]
FYI, we confirmed adoption on the list (also for -invariants)

**Comment by janaiyengar** [comment]
Let's get this doc in and make changes from there. Merging.

**Pull request merged**
