### PR TITLE
Move sec on ignoring loss to loss detection section

### PR DESCRIPTION
**Pull request by mirjak**
I seems this section is misplaced as it talks about loss detection.

### CODE REVIEW

**Comment by ianswett** [comment]
It only discusses their impact on congestion control, so I think it's in the right place.

**Comment by mirjak** [comment]
Detection loss has impact on congestion control but the text describes only if something should be counted/detected as loss or not. I found it misplaced where it is but feel free to close this.

**Comment by ianswett** [comment]
#3450 changes this text substantially and adds corresponding pseudocode, so it's worth a look at that.  If you still would like more changes, let's land them after that change.

**Comment by mirjak** [comment]
yep makes sense

**Pull request closed without merging**
